<a href="https://colab.research.google.com/github/adityasingh1993/MachineLearningBasic/blob/master/Numpy_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy is the most basic and a powerful package for working with data in python.
Because other packages for data analysis (like pandas) is built on top of numpy and the scikit-learn package which is used to build machine learning applications works heavily with numpy as well.NumPy is a linear algebra library for Python

At the core, numpy provides the excellent ndarray objects, short for n-dimensional arrays.


1.Arrays support vectorised operations, while lists don’t.

2.Once an array is created, you cannot change its size. You will have to create a new array or overwrite the existing one.

3.Every array has one and only one dtype. All items in it should be of that dtype.

4.An equivalent numpy array occupies much less space than a python list of lists

In [ ]:
! wget https://www.thesprucepets.com/thmb/aB6Dj_ZD9iulkqn7wzFynzFuz5Q=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/horse-galloping-in-grass-688899769-587673275f9b584db3a44cdf.jpg

/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: ` wget https://www.thesprucepets.com/thmb/aB6Dj_ZD9iulkqn7wzFynzFuz5Q=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/horse-galloping-in-grass-688899769-587673275f9b584db3a44cdf.jpg'


#How to create a numpy array?

# New Section

In [ ]:
import numpy as np
list1 = [0,1,2,3,4]
arr1d = np.array(list1)

# Print the array and its type
print(type(arr1d))
arr1d

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4])

In [ ]:
np.array(1).shape

()

In [ ]:
# Create a 2d array from a list of lists

list2 = [[0,1,2], [3,4,5], [6,7,8]]
arr2d = np.array(list2)

print(arr2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#numpy.zeros(shape, dtype=float )
array3 = np.zeros((2,3)) #array of zeroes 2 rows long by 3 columns wide
print(array3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#numpy.ones(shape, dtype=float )
array4 = np.ones((2,2)) #array of ones 2 rows long by 2 columns wide
array4

array([[1., 1.],
       [1., 1.]])

In [ ]:
#numpy.identity(n, dtype=None)
#Identity Matrix, A*(inv(A))=I
array5 = np.identity(3) #identity matrix with dimension of 3
array5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
import numpy as np
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#numpy.full(shape, fill_value, dtype=None)
np.full((3,4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

#How to create sequences, repetitions and random numbers using numpy?

In [ ]:
# Lower limit is 0 be default
#print(np.arange(2,10))

# 0 to 9
#print(np.arange(0, 10))  

# # 0 to 9 with step of 2
print(np.arange(0, 10, 2))  

# # 10 to 1, decreasing order
#print(np.arange(10, 0, -1))

[0 2 4 6 8]


In [ ]:
#Create Repeating Sequence
#numpy.tile(A, reps)
a = [1,2,3] 

# Repeat whole of 'a' two times
print('Tile:   ', np.tile(a, 2))

# Repeat each element of 'a' two times
print('Repeat: ', np.repeat(a, 3))

Tile:    [1 2 3 1 2 3]
Repeat:  [1 1 1 2 2 2 3 3 3]


In [ ]:
#Generate random numbers

# Random numbers between [0,1] of shape 2,2
#print(np.random.rand(2,2))

#  Normal distribution with mean=0 and variance=1 of shape 2,2
#np.random.rand(3,4)

# # Random integers between [0, 10) of shape 2,2
print(np.random.randint(0, 10,3))

# One random number between [0,1)
#np.random.randn(3,4)
      


[9 0 5]


In [ ]:
# Start at 1 and end at 50
np.linspace(start=1, stop=50, num=10,dtype=int)

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50])

#Creating sample data from data set

In [ ]:
np.random.choice(['a', 'e', 'i', 'o', 'u','u','m'], size=3)

# Pick 10 items from a given list with a predefined probability 'p'
#print(np.random.choice(['a', 'e', 'i', 'o', 'u','a'], size=3, p=[0.3, .1, 0.1, 0.3, 0.1,.1]))

array(['m', 'e', 'o'], dtype='<U1')

In [ ]:
# Create the random state(If you want to create same set of random number)

rn = np.random.RandomState(30)

# Create random numbers between [0,1) of shape 2,2

print(rn.rand(2,2))


# Set the random seed

#np.random.seed(40)

# Create random numbers between [0,1) of shape 2,2

#print(np.random.rand(2,2))

[[0.64414354 0.38074849]
 [0.66304791 0.16365073]]


In [ ]:
#Getting Unique numbers or items
# Get the unique items and their counts

np.random.seed(100)
arr_rand = np.random.randint(0, 10, size=10)
print(arr_rand)
uniqs, counts = np.unique(arr_rand, return_counts=True)
print("Unique items : ", uniqs)
print("Counts       : ", counts)

[8 8 3 7 7 0 4 2 5 2]
Unique items :  [0 2 3 4 5 7 8]
Counts       :  [1 2 1 1 1 2 2]


In [ ]:
# mean, max and min
list2 = [[0,1,2], [3,4,5], [6,7,8]]
arr2 = np.array(list2)

print("Mean value is: ", arr2.mean())
print("Max value is: ", arr2.max())
print("Min value is: ", arr2.min())

# shape
print('Shape: ', arr2.shape)

# dtype
print('Datatype: ', arr2.dtype)

# size
print('Size: ', arr2.size)

# ndim
print('Num Dimensions: ', arr2.ndim)

Mean value is:  4.0
Max value is:  8
Min value is:  0
Shape:  (3, 3)
Datatype:  int64
Size:  9
Num Dimensions:  2


In [ ]:
list2 = [[0,1,2], [3,4,5], [6,7,8]]
arr2 = np.array(list2)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Extract the first 2 rows and columns

arr2[:, 0:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
list2 = [[0,1,2], [3,4,5], [6,7,8]]
arr2 = np.array(list2)
print(arr2)
index_gt5 = np.where(arr2 <2 )
print("Positions where value > 2: ", index_gt5)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Positions where value > 2:  (array([0, 0]), array([0, 1]))


In [ ]:
#concatenate two numpy arrays columnwise and row wise

# Method 1: np.concatenate by changing the axis parameter to 0 and 1
# Method 2: np.vstack and np.hstack
# Method 3: np.r_ and np.c_
a = np.zeros([4, 3])
b = np.ones([4, 3])
print(a)
print(b)

 
#np.vstack([a,b])  
#np.r_[a,b]  

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Vertical Stack Equivalents (Row wise)
np.concatenate([a, b], axis=1) 

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [ ]:
# Horizontal Stack Equivalents (Coliumn wise)
np.concatenate([a, b], axis=1) 
#np.hstack([a,b])  
#np.c_[a,b]

array([[0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1.]])

In [ ]:
#Sorting an Array

arr = np.random.randint(1,6, size=[8, 4])

# Sort each columns of arr
np.sort(arr, axis=0)

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [2, 3, 4, 2],
       [2, 4, 4, 3],
       [3, 4, 4, 3],
       [3, 4, 4, 5],
       [3, 4, 5, 5],
       [4, 5, 5, 5]])

In [ ]:
# Create a datetime64 object
date64 = np.datetime64('2018-02-04 23:10:10')
date64

# Create date sequence
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-10'))
print(dates)

# Check if its a business day
np.is_busday(dates)

['2018-02-01' '2018-02-02' '2018-02-03' '2018-02-04' '2018-02-05'
 '2018-02-06' '2018-02-07' '2018-02-08' '2018-02-09']


array([ True,  True, False, False,  True,  True,  True,  True,  True])

In [ ]:
# Reverse the row and column positions
arr2[::-1, ::-1]

In [ ]:
print(np.random.randint(0, 10,4))

[3 0 1 3]


In [ ]:
print(np.random.choice(['a', 'e', 'i', 'o', 'u','a','a'], size=3, p=[0.3, .1, 0.1, 0.2, 0.1,0.1, 0.1]))

['o' 'u' 'e']


In [ ]:
def make_pretty(func):
    def inner():
        print("I got decorated")
        func()
    return inner

def ordinary():
    print("I am ordinary")

In [ ]:
@make_pretty
def ordinary():
  print("I am ordinary")

In [ ]:
ordinary()

I got decorated
I am ordinary


In [ ]:
adult =list(range(10))
print(adult)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
